spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver  
    url: jdbc:mysql://10.19.10.34:3306/aidoscrum?useUnicode=true&characterEncoding=utf8&useSSL=false&allowMultiQueries=true
    username: aidoscrum
    password: scrum@123
  redis:
    host: 10.1.234.29
    port: 16379
file: 
  server: http://10.19.10.35:18080/
  upload: /fdata/aido/aido-agile/upload
  template: /fdata/aido/aido-agile/template
mail:
  server:
    host: mail.asiainfo.com
    port: 25
    protocol: smtp
    username: aisw_qmc@asiainfo.com
    password: Ice-cream
    address: http://10.19.10.35:8080
    from: aisw_qmc@asiainfo.com
multipart:
  temp: 
    location: /fdata/aido/tmp
cmp:
  enable: false
  host: 10.19.10.35
  port: 27000
  context: /cmp
  cicd:
    url: http://10.1.242.49:8820
  ci:
    buildDeployUrl: http://10.19.18.46:8762/cms/data/dashBoardInterface/qryBuildOrDeployFlowInfoByScene.action
    compileDeployTimesUrl: http://10.19.18.46:8762/cms/data/dashBoardInterface/qryLastFiveTimeResultByFlowId.action
