spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver  
    url: jdbc:mysql://10.19.10.34:3306/aidouser?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: aidouser
    password: user@123
admin: 
  account: admin
  password: aido@35