spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver  
    url: jdbc:mysql://10.19.10.34:3306/aidouser?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: aidouser
    password: user@123
  redis:
    host: 10.1.234.29
    port: 16379
file:
  server: http://10.19.10.35:18080/